# Generated by Django 5.1 on 2024-08-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_combo"),
    ]

    operations = [
        migrations.AddField(
            model_name="combo",
            name="image_url",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
